galaxy_info:
  author: yunus.cogal
  role_name: forti_netbox_public_ip
  description: Read FortiGate WAN/public IPv4 and IPv6 addresses and synchronize them to NetBox interfaces.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - "11"
        - "12"

dependencies: []
